/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedWorkspacesIndexRouteImport } from './routes/_authed/workspaces/index'
import { Route as AuthedWorkspacesWorkspaceSlugRouteImport } from './routes/_authed/workspaces/$workspaceSlug'
import { Route as AuthedWorkspacesWorkspaceSlugNotesNoteIdRouteImport } from './routes/_authed/workspaces/$workspaceSlug.notes.$noteId'
import { Route as AuthedWorkspacesWorkspaceSlugNotesNoteIdIndexRouteImport } from './routes/_authed/workspaces/$workspaceSlug.notes.$noteId.index'
import { Route as AuthedWorkspacesWorkspaceSlugNotesNoteIdHistoryRouteImport } from './routes/_authed/workspaces/$workspaceSlug.notes.$noteId.history'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkspacesIndexRoute = AuthedWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkspacesWorkspaceSlugRoute =
  AuthedWorkspacesWorkspaceSlugRouteImport.update({
    id: '/workspaces/$workspaceSlug',
    path: '/workspaces/$workspaceSlug',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedWorkspacesWorkspaceSlugNotesNoteIdRoute =
  AuthedWorkspacesWorkspaceSlugNotesNoteIdRouteImport.update({
    id: '/notes/$noteId',
    path: '/notes/$noteId',
    getParentRoute: () => AuthedWorkspacesWorkspaceSlugRoute,
  } as any)
const AuthedWorkspacesWorkspaceSlugNotesNoteIdIndexRoute =
  AuthedWorkspacesWorkspaceSlugNotesNoteIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedWorkspacesWorkspaceSlugNotesNoteIdRoute,
  } as any)
const AuthedWorkspacesWorkspaceSlugNotesNoteIdHistoryRoute =
  AuthedWorkspacesWorkspaceSlugNotesNoteIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthedWorkspacesWorkspaceSlugNotesNoteIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/workspaces/$workspaceSlug': typeof AuthedWorkspacesWorkspaceSlugRouteWithChildren
  '/workspaces/': typeof AuthedWorkspacesIndexRoute
  '/workspaces/$workspaceSlug/notes/$noteId': typeof AuthedWorkspacesWorkspaceSlugNotesNoteIdRouteWithChildren
  '/workspaces/$workspaceSlug/notes/$noteId/history': typeof AuthedWorkspacesWorkspaceSlugNotesNoteIdHistoryRoute
  '/workspaces/$workspaceSlug/notes/$noteId/': typeof AuthedWorkspacesWorkspaceSlugNotesNoteIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthedIndexRoute
  '/workspaces/$workspaceSlug': typeof AuthedWorkspacesWorkspaceSlugRouteWithChildren
  '/workspaces': typeof AuthedWorkspacesIndexRoute
  '/workspaces/$workspaceSlug/notes/$noteId/history': typeof AuthedWorkspacesWorkspaceSlugNotesNoteIdHistoryRoute
  '/workspaces/$workspaceSlug/notes/$noteId': typeof AuthedWorkspacesWorkspaceSlugNotesNoteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/workspaces/$workspaceSlug': typeof AuthedWorkspacesWorkspaceSlugRouteWithChildren
  '/_authed/workspaces/': typeof AuthedWorkspacesIndexRoute
  '/_authed/workspaces/$workspaceSlug/notes/$noteId': typeof AuthedWorkspacesWorkspaceSlugNotesNoteIdRouteWithChildren
  '/_authed/workspaces/$workspaceSlug/notes/$noteId/history': typeof AuthedWorkspacesWorkspaceSlugNotesNoteIdHistoryRoute
  '/_authed/workspaces/$workspaceSlug/notes/$noteId/': typeof AuthedWorkspacesWorkspaceSlugNotesNoteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/workspaces/$workspaceSlug'
    | '/workspaces/'
    | '/workspaces/$workspaceSlug/notes/$noteId'
    | '/workspaces/$workspaceSlug/notes/$noteId/history'
    | '/workspaces/$workspaceSlug/notes/$noteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/workspaces/$workspaceSlug'
    | '/workspaces'
    | '/workspaces/$workspaceSlug/notes/$noteId/history'
    | '/workspaces/$workspaceSlug/notes/$noteId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/'
    | '/_authed/workspaces/$workspaceSlug'
    | '/_authed/workspaces/'
    | '/_authed/workspaces/$workspaceSlug/notes/$noteId'
    | '/_authed/workspaces/$workspaceSlug/notes/$noteId/history'
    | '/_authed/workspaces/$workspaceSlug/notes/$noteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workspaces/': {
      id: '/_authed/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthedWorkspacesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workspaces/$workspaceSlug': {
      id: '/_authed/workspaces/$workspaceSlug'
      path: '/workspaces/$workspaceSlug'
      fullPath: '/workspaces/$workspaceSlug'
      preLoaderRoute: typeof AuthedWorkspacesWorkspaceSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workspaces/$workspaceSlug/notes/$noteId': {
      id: '/_authed/workspaces/$workspaceSlug/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/workspaces/$workspaceSlug/notes/$noteId'
      preLoaderRoute: typeof AuthedWorkspacesWorkspaceSlugNotesNoteIdRouteImport
      parentRoute: typeof AuthedWorkspacesWorkspaceSlugRoute
    }
    '/_authed/workspaces/$workspaceSlug/notes/$noteId/': {
      id: '/_authed/workspaces/$workspaceSlug/notes/$noteId/'
      path: '/'
      fullPath: '/workspaces/$workspaceSlug/notes/$noteId/'
      preLoaderRoute: typeof AuthedWorkspacesWorkspaceSlugNotesNoteIdIndexRouteImport
      parentRoute: typeof AuthedWorkspacesWorkspaceSlugNotesNoteIdRoute
    }
    '/_authed/workspaces/$workspaceSlug/notes/$noteId/history': {
      id: '/_authed/workspaces/$workspaceSlug/notes/$noteId/history'
      path: '/history'
      fullPath: '/workspaces/$workspaceSlug/notes/$noteId/history'
      preLoaderRoute: typeof AuthedWorkspacesWorkspaceSlugNotesNoteIdHistoryRouteImport
      parentRoute: typeof AuthedWorkspacesWorkspaceSlugNotesNoteIdRoute
    }
  }
}

interface AuthedWorkspacesWorkspaceSlugNotesNoteIdRouteChildren {
  AuthedWorkspacesWorkspaceSlugNotesNoteIdHistoryRoute: typeof AuthedWorkspacesWorkspaceSlugNotesNoteIdHistoryRoute
  AuthedWorkspacesWorkspaceSlugNotesNoteIdIndexRoute: typeof AuthedWorkspacesWorkspaceSlugNotesNoteIdIndexRoute
}

const AuthedWorkspacesWorkspaceSlugNotesNoteIdRouteChildren: AuthedWorkspacesWorkspaceSlugNotesNoteIdRouteChildren =
  {
    AuthedWorkspacesWorkspaceSlugNotesNoteIdHistoryRoute:
      AuthedWorkspacesWorkspaceSlugNotesNoteIdHistoryRoute,
    AuthedWorkspacesWorkspaceSlugNotesNoteIdIndexRoute:
      AuthedWorkspacesWorkspaceSlugNotesNoteIdIndexRoute,
  }

const AuthedWorkspacesWorkspaceSlugNotesNoteIdRouteWithChildren =
  AuthedWorkspacesWorkspaceSlugNotesNoteIdRoute._addFileChildren(
    AuthedWorkspacesWorkspaceSlugNotesNoteIdRouteChildren,
  )

interface AuthedWorkspacesWorkspaceSlugRouteChildren {
  AuthedWorkspacesWorkspaceSlugNotesNoteIdRoute: typeof AuthedWorkspacesWorkspaceSlugNotesNoteIdRouteWithChildren
}

const AuthedWorkspacesWorkspaceSlugRouteChildren: AuthedWorkspacesWorkspaceSlugRouteChildren =
  {
    AuthedWorkspacesWorkspaceSlugNotesNoteIdRoute:
      AuthedWorkspacesWorkspaceSlugNotesNoteIdRouteWithChildren,
  }

const AuthedWorkspacesWorkspaceSlugRouteWithChildren =
  AuthedWorkspacesWorkspaceSlugRoute._addFileChildren(
    AuthedWorkspacesWorkspaceSlugRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedWorkspacesWorkspaceSlugRoute: typeof AuthedWorkspacesWorkspaceSlugRouteWithChildren
  AuthedWorkspacesIndexRoute: typeof AuthedWorkspacesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedWorkspacesWorkspaceSlugRoute:
    AuthedWorkspacesWorkspaceSlugRouteWithChildren,
  AuthedWorkspacesIndexRoute: AuthedWorkspacesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
